AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Allium: CFN Template to create an EC2 instance.

Metadata:
  TemplateName: ec2-stack.yaml
  TemplateType: EC2 Instance
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Allium
  Modification History:
    - 1.0.0  - Jul 02, 2024   -- Initial Version 
  Resources: 
    - EC2 instance
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name and Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyArn
    #################################### EC2 #######################################################
    - Label: 
        default: "EC2 Instance Configuration:"
      Parameters: 
        - NameTag
        - EC2InstanceType
        - EC2ImageId
        - SubnetId
        - EC2SecurityGroupId
        - EFSSecurityGroupId
        - EC2InstanceProfile
        - AssignPublicIPAddress
        - PrivateIPAddress
        - ElasticFileSystemId
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project name."
      Environment:
        default: "Environment name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub workflow run number."
      GitHubSHA:
        default: "GitHub SHA."
      GitHubRepository:
        default: "GitHub repository."
      CiBuild:
        default: "Ci build."
      ################################## KMS Key ###################################################
      KmsMasterKeyArn: 
        default: "Kms key arn."
      ################################### EC2  #####################################################
      NameTag: 
        default: EC2 name tag
      EC2InstanceType:
        default: Type of EC2 instance to launch for the server.
      EC2ImageId:
        default: EC2 Image Id.
      SubnetId:
        default: The Subnet where the EC2 instance will be created.
      EC2SecurityGroupId: 
        default: EC2 Security Group Id
      EFSSecurityGroupId: 
        default: EFS Security Group Id
      EC2InstanceProfile: 
        default: EC2 Instance Profile
      AssignPublicIPAddress:
        default: Assign public IP address
      PrivateIPAddress: 
        default: "Private IP address of the EC2 instance."
      ElasticFileSystemId: 
        default: "EFS Id"
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: allium
    Description: "The project name that will be used as resource name prefixes and will be used to tag resources to track the project cost."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The deployment environment (dev/test/prod)."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub ref name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The GitHub workflow run number for the latest CI/CD pipeline."
    Type: Number
  GitHubSHA:
    Default: "27e994ee4b064c37170c9a702c44b676c3295e1f"
    Description: "The sha value of the last commit."
    Type: String
  GitHubRepository:
    Default: 0032-allium-cft
    Description: "The GitHub repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### KMS Key ###################################################
  KmsMasterKeyArn:
    Default: "arn:aws:kms:us-east-1:637423502513:key/494509e4-3bc5-44b8-9c4d-12449900d395"
    Description: "The KMS key arn used to encrypt the resources."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ###################################### EC2 #######################################################
  NameTag: 
    Default: "EFS Mount Test"
    Description: Name of the EC2 instance
    Type: String
    MinLength: 10
    MaxLength: 30
  EC2InstanceType:
    Description: Type of ec2 instance to launch for the server.
    Type: String
    Default: t2.micro
    ConstraintDescription: Must be a valid EC2 instance type
    AllowedValues: 
      - t2.nano
      - t2.micro
      - t2.small
  EC2ImageId:
    Description: Image Id To Be Used To Launch The EC2 Instance.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EC2SecurityGroupId: 
    Default: "sg-0b7ddca47a2aebe49"
    Description: "Security Group Id for the EC2 instance"
    Type: String
  EFSSecurityGroupId: 
    Default: "sg-019776a359d0098f3"
    Description: "Security Group Id for the Elastic File System"
    Type: String
  SubnetId:
    Default: "subnet-0e8280f76c47e475e"
    Description: VPC Subnet where the EC2 instance will be launched.
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: "[a-z0-9-]*"
  EC2InstanceProfile:
    Default: "allium-instance-profile-devl"
    Description: "EC2 Instance Profile."
    Type: String
  AssignPublicIPAddress: 
    Default: "true"
    Description: Automatically assign a public IP address
    Type: String
    AllowedValues: ["true", "false"]
  PrivateIPAddress: 
    Default: "10.0.0.101"
    Description: Private IP Address of the EC2 instance
    Type: String
  ElasticFileSystemId:
    Default: "fs-0a514b4044587c4ee"
    Description: Elastic File System Id
    Type: String
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      "AWS::CloudFormation::Init":
        config: 
          packages: 
            dnf:
              amazon-efs-utils: []
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
                verbose=true
              mode: '000400'
              owner: 'root'
              group: 'root'
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2Instance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: 'root'
              group: 'root'
          commands: 
            01_create_efs_dir:
              command: !Sub "sudo mkdir -p /efs/${ProjectName}"
              cwd: "~"
              test: !Sub "test ! -d /efs/${ProjectName}"
              ignoreErrors: "false"
            02_add_entry_fstab:
              command: !Sub "echo '${ElasticFileSystemId}.efs.${AWS::Region}.amazonaws.com:/ /efs/${ProjectName} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0' >>  /etc/fstab"
              cwd: "~"
              test: "cat /etc/fstab"
              ignoreErrors: "false"
            03_wait_for_efs_active_status: 
              command: sleep 300
              ignoreErrors: "false"
            04_mount_efs: 
              command: !Sub "sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${ElasticFileSystemId}.efs.${AWS::Region}.amazonaws.com:/ /efs/${ProjectName}"
              cwd: "~"
              test: "df -k"
              ignoreErrors: "false"
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
    
    # Creation Policy will ensure that if the instance isn't complete within the specified window, that a rollback will occur
    CreationPolicy:
      ResourceSignal:
        Count: '1'
        Timeout: PT15M

    Properties:
      InstanceType: !Ref EC2InstanceType
      ImageId: !Ref EC2ImageId
      IamInstanceProfile: !Ref EC2InstanceProfile
      PropagateTagsToVolumeOnCreation: "true"
      BlockDeviceMappings:
      - DeviceName: /dev/xvda     #sdb
        Ebs:
          Encrypted: "true"
          KmsKeyId: !Ref KmsMasterKeyArn
          DeleteOnTermination: "true"
          VolumeType: gp2
          VolumeSize: 8
      NetworkInterfaces: 
      - AssociatePublicIpAddress: !Ref AssignPublicIPAddress
        DeviceIndex: "0"
        DeleteOnTermination: true
        GroupSet: 
          - !Ref EC2SecurityGroupId
          - !Ref EFSSecurityGroupId
        SubnetId: !Ref SubnetId
        PrivateIpAddresses: 
        - Primary: "true"
          PrivateIpAddress: !Ref PrivateIPAddress
      UserData: !Base64
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region} 
      Tags:
        - Key: Name
          Value: !Ref NameTag
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
        - Key: CiBuild
          Value: !Ref CiBuild
Outputs:
  EC2InstanceId:
    Description: The EC2 Instance Id.
    Value: !Ref EC2Instance
  EC2PrivateIP:
    Description: The EC2 instance Private IP
    Value: !GetAtt EC2Instance.PrivateIp
  EC2PublicIP:
    Description: The EC2 instance Public IP
    Value: !GetAtt EC2Instance.PublicIp

